### ISSUE TITLE
Investigations of storing multiple types in separate buffers in one allocation

### ISSUE THREAD

**Issue by makoConstruct** [vadixidav/header-vec#7]
> ... For me **the largest improvement would actually be if I could store multiple types in separate buffers in the allocation rather than as tuples**

_Originally posted by @vadixidav in https://github.com/rust-cv/header-vec/issues/4#issuecomment-899149076_

**Comment by makoConstruct** [comment]
On this, I've just sort of maybe finished up working on something very closely related to that, [`VecWithGaps`](https://github.com/makoConstruct/vec-with-gaps), and I can report that it did not go well. Once you have multiple inner vecs, The increased adjacency just doesn't seem to be doing much. I don't really feel that I understand what is going on here, yet, though. Performance remains unimpressive even when the extra capacity of all of the inner vecs is trimmed out, and even when there's a large number of small subvecs.

**Comment by vadixidav** [comment]
> On this, I've just sort of maybe finished up working on something very closely related to that, [`VecWithGaps`](https://github.com/makoConstruct/vec-with-gaps), and I can report that it did not go well. Once you have multiple inner vecs, The increased adjacency just doesn't seem to be doing much. I don't really feel that I understand what is going on here, yet, though. Performance remains unimpressive even when the extra capacity of all of the inner vecs is trimmed out, and even when there's a large number of small subvecs.

Interesting. I would be curious to see how it performs with SIMD operations as well, but I suppose even with tuples things are "close enough" in memory already. In my code, each tuple already contains a (usize, 512-bit chunk), where the 512-bit chunk can use SIMD, so its already separated and aligned such that SIMD is possible. The reason why I was interested in this is because the memory could be more compact than it currently is. Currently, I am wasting a lot of space because the usize and the 512-bit chunk are not the same size, but the 512-bit chunk needs to be aligned for SIMD. Perhaps you could investigate this scenario?

**Comment by makoConstruct** [comment]
Hmm I think it wouldn't be too hard to fit all of these things into
vecwithgaps, but I wont do it just now. Moving onto implementing CSR++.

**Comment by vadixidav** [comment]
I think I will go ahead and close this. I think this investigation has concluded for now. Open another ticket if this comes up again.
